language: python
python:
- '3.6'
- '3.7'
- '3.8'
- 3.8-dev
- nightly
install:
- pip install -r requirements.txt
script:
- pre-commit run --all-files
- pytest
deploy:
  provider: pypi
  user: __token__
  password:
    secure: JS+rBoPD0s71T8uBq/P6Y1n8pUk0X7hgKVKRS3z9E1hhdognGKb6fOWqN41gRTmo0KU7HvWHO83t7Jem0xHBdLOsgcQoo0J0y3L8nMPDVPvocRNMfYD3yYPTnwBJOxaS3OkOoYbmoEXRumDoA4yOlrncvGpy839kN60pRWpGwhuCni1/odg2+PeC9MuT2621fVgKKxyCyOGj9HrmDIXWOCd1AK2c95KL8rtRISXdNRSP9SgwqFRrDgkBIsFLNFfDYDbWfHxgLf/dvmMjyT5ijgm7g1dqlDMTKHnbP4d1rrsH5TJdDBrB2CWnbxg7cWl+Ahc7ADt6rD1FRqB+Npulu/KAdiqYHRAOVGyPfBWKf+RdtsJ2JohKLIVcgjPChOe7lXnHfvjSbGF9ju9UpGP0xFj8y8FkvL9ULJe4Dpcantp6Z7h3qwdAlrhwH6h4132zJi/v86OJJdJiMKLoqtHP6n1W/3DJLMfsco/Q69a4Jdo8tPrkBST3UuMMOqsN6nDv6VjFreDmGYMy0Dt6V2GVtncNRsVCD2ircvJjvnXKQHU6Zln1jfx51zQ+98QfNsGllY4/nQ435meqH6Lbfg17sjy50JuTn4anEQwVWTJlwZlA9kkuvK7fqdDLPXu+opSCrXSP8m7yWhpGQxKRBdxA3vcRKStTunoSi7z7X9mvAp0=
  skip_existing: true
  on:
    tags: true
